<<<<<<< HEAD
#Define NodePort Service with nodePort:31000, port:8080 and targetPort:9090
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubernetes-rabbitmq-consumer
    version: v1
  name: kubernetes-rabbitmq-consumer
spec:
  ports:
    -
      name: http
      port: 8080
      targetPort: 9090
      nodePort: 31001
  selector:
    app: kubernetes-rabbitmq-consumer
    version: v1
  type: NodePort
---
#Define deployment using the image pushed to Docker Hub.
#Get environment variables from secret and name it as `RABBITMQ_USERNAME` and `RABBITMQ_PASSWORD`
#Use containerPort 9090
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubernetes-rabbitmq-consumer
    version: v1
  name: kubernetes-rabbitmq-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-rabbitmq-consumer
      version: v1
  template:
    metadata:
      labels:
        app: kubernetes-rabbitmq-consumer
        version: v1
    spec:
      containers:
        -
          image: "kavipriyasdocker/rabbitmqconsumer"
          imagePullPolicy: Always
          name: rabbitmq-producer
          env:
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmqsecret
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmqsecret
                  key: password
          ports:
            -
              containerPort: 9090
              name: http
=======
#Define NodePort Service with nodePort:31000, port:8080 and targetPort:9090
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubernetes-rabbitmq-consumer
    version: v1
  name: kubernetes-rabbitmq-consumer
spec:
  ports:
    -
      name: http
      port: 8080
      targetPort: 9090
      nodePort: 31001
  selector:
    app: kubernetes-rabbitmq-consumer
    version: v1
  type: NodePort
---
#Define deployment using the image pushed to Docker Hub.
#Get environment variables from secret and name it as `RABBITMQ_USERNAME` and `RABBITMQ_PASSWORD`
#Use containerPort 9090
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubernetes-rabbitmq-consumer
    version: v1
  name: kubernetes-rabbitmq-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-rabbitmq-consumer
      version: v1
  template:
    metadata:
      labels:
        app: kubernetes-rabbitmq-consumer
        version: v1
    spec:
      containers:
        -
          image: "kavipriyasdocker/rabbitmqconsumer"
          imagePullPolicy: Always
          name: rabbitmq-producer
          env:
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmqsecret
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmqsecret
                  key: password
          ports:
            -
              containerPort: 9090
              name: http
>>>>>>> 52412339bd02cb63d20ab71215d91f8f3f037b97
              protocol: TCP