<<<<<<< HEAD
#Define Secret to hold erlang-cookie, username and password
apiVersion: v1
kind: Secret
metadata:
    name: rabbitmqsecret
type: Opaque
data:
   username : Z3Vlc3Q=
   password : Z3Vlc3Q=
=======
#Define Secret to hold erlang-cookie, username and password
apiVersion: v1
kind: Secret
metadata:
    name: rabbitmqsecret
type: Opaque
data:
   username : Z3Vlc3Q=
   password : Z3Vlc3Q=
>>>>>>> 52412339bd02cb63d20ab71215d91f8f3f037b97
   erlang-cookie : Yy1pcy1mb3ItY29va2llLXRoYXRzLWdvb2QtZW5vdWdoLWZvci1tZQ==