<<<<<<< HEAD
#Define service of type NodePort to expose the management HTTP port on each node and name it as rabbitmq-management
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
  labels:
    app: rabbitmq
spec:
  ports:
  - port: 15672
    name: http
  selector:
    app: rabbitmq
  type: NodePort
---
#Define the required headless service for StatefulSets and name it as rabbitmq
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  ports:
  - port: 5672
    name: amqp
  - port: 4369
    name: epmd
  - port: 25672
    name: rabbitmq-dist
  clusterIP: None
  selector:
    app: rabbitmq
---
#Define RabbitMQ StatefulSet using `rabbitmq:3.7.5-management` image configuring service and replicas.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  replicas: 1
  serviceName: rabbitmq
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.7.5-management
        env:
        - name: "RABBITMQ_ERLANG_COOKIE"
          valueFrom:
            secretKeyRef:
              name: rabbitmqsecret
              key: erlang-cookie
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-data
      volumes:
        - name: rabbitmq-data
          hostPath:
            path: /data/rabbitmq
=======
#Define service of type NodePort to expose the management HTTP port on each node and name it as rabbitmq-management
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
  labels:
    app: rabbitmq
spec:
  ports:
  - port: 15672
    name: http
  selector:
    app: rabbitmq
  type: NodePort
---
#Define the required headless service for StatefulSets and name it as rabbitmq
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  ports:
  - port: 5672
    name: amqp
  - port: 4369
    name: epmd
  - port: 25672
    name: rabbitmq-dist
  clusterIP: None
  selector:
    app: rabbitmq
---
#Define RabbitMQ StatefulSet using `rabbitmq:3.7.5-management` image configuring service and replicas.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  replicas: 1
  serviceName: rabbitmq
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.7.5-management
        env:
        - name: "RABBITMQ_ERLANG_COOKIE"
          valueFrom:
            secretKeyRef:
              name: rabbitmqsecret
              key: erlang-cookie
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-data
      volumes:
        - name: rabbitmq-data
          hostPath:
            path: /data/rabbitmq
>>>>>>> 52412339bd02cb63d20ab71215d91f8f3f037b97
            type: DirectoryOrCreate