#Create the service of type nodePort and use the created deployment as selector
# Use port 8081
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubernetes-excercise-rollout
    version: v1
  name: kubernetes-excercise-rollout
spec:
  ports:
    -
      name: http
      port: 8081
      targetPort: 8081
  selector:
    app: kubernetes-excercise-rollout
    version: v1
  type: NodePort
