apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubernetes-spring-demo
    version: v1
  name: config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-spring-demo
      version: v1
  template:
    metadata:
      labels:
        app: kubernetes-spring-demo
        version: v1
    spec:
      containers:
        -
          image: "kavipriyasdocker/kubernetes-spring-boot"
          imagePullPolicy: Always
          name: kubernetes-spring-boot
          ports:
            -
              containerPort: 8080
              name: http
              protocol: TCP
