apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubernetes-spring-demo
    version: v1
  name: kubernetes-spring-demo
spec:
  ports:
    -
      name: http
      port: 8080
      targetPort: 8080
  selector:
    app: kubernetes-spring-demo
    version: v1
  type: NodePort
