
app:
  rabbitmq:
    exchange: employeeexchange
    queue: employeequeue
    routingkey: employeeroutingkey
  message: Message sent to the RabbitMQ queue Successfully
spring:
  rabbitmq:
    #use the rabbitmq headless service name as host
    host: 172.17.0.4
    #get the username and password from secret. For example: ${<environment variable name>}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

    port: 5672
server:
  port: 9090
