#Create a deployment by using the image pushed to Docker Hub
#Use containerPort 4200
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubernetes-frontend
    version: v1
  name: kubernetes-frontend
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: kubernetes-frontend
      version: v1
  template:
    metadata:
      labels:
        app: kubernetes-frontend
        version: v1
    spec:
      containers:
        -
          image: "kavipriyasdocker/kubernetes-frontend"
          imagePullPolicy: Always
          name: kubernetes-frontend
          ports:
            -
              containerPort: 4200
              name: http
              protocol: TCP
---
#Create the service of type NodePort and use the created deployment as selector
# Use port 4200
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubernetes-frontend
    version: v1
  name: kubernetes-frontend
spec:
  ports:
    -
      name: http
      port: 4200
      targetPort: 4200
  selector:
    app: kubernetes-frontend
    version: v1
  type: NodePort


