#Create a deployment by using the image pushed to Docker Hub
#Use containerPort 8081
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubernetes-spring-angular-demo
    version: v1
  name: kubernetes-spring-angular-demo
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: kubernetes-spring-angular-demo
      version: v1
  template:
    metadata:
      labels:
        app: kubernetes-spring-angular-demo
        version: v1
    spec:
      containers:
        -
          image: "kavipriyasdocker/kubernetes-spring-angular-demo"
          imagePullPolicy: Always
          name: kubernetes-spring-angular-demo
          ports:
            -
              containerPort: 8081
              name: http
              protocol: TCP

---
#Create the service of type NodePort and use the created deployment as selector
#Use port 8081
#Assign nodePort to some port in valid range, so that it can be used in angular
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubernetes-spring-angular-demo
    version: v1
  name: kubernetes-spring-angular-demo
spec:
  ports:
    -
      name: http
      port: 8081
      targetPort: 8081
  selector:
    app: kubernetes-spring-angular-demo
    version: v1
  type: NodePort

